USE w2l_db_dev;

DELIMITER $$
DROP TRIGGER IF EXISTS TR_AFTER_INSERT_ON_VIDEOS $$

CREATE TRIGGER TR_AFTER_INSERT_ON_VIDEOS
AFTER INSERT
ON Videos FOR EACH ROW
BEGIN
	UPDATE Lessons AS L
	SET
		L.content_type = 1
	WHERE
		L.id_lesson = new.lesson_id;
END $$
DELIMITER ;